name: 'Calculator Action'
description: 'Performs basic arithmetic calculations'

inputs:
  number1:
    description: 'The first number'
    required: true
  number2:
    description: 'The second number'
    required: true
  operation:
    description: 'The operation to perform (addition, subtraction, multiplication, division)'
    required: true

outputs:
  result:
    description: 'The result of the calculation'

runs:
  using: 'composite'
  outputs:
    result: ${{ steps.result-output.outputs.result }}
  steps:
    - name: Checking out Repository
      uses: actions/checkout@v2
      
    - name: Calculate
      shell: 'bash'
      id: result-output
      run: |
        number1=${{ inputs.number1 }}
        number2=${{ inputs.number2 }}
        operation=${{ inputs.operation }}
        $result = ${{ inputs.num1 }}${{ inputs.operator }}${{ inputs.num2 }}
        
        echo result=$result >> $env:GITHUB_OUTPUT
        echo 'Result of calculation is ${{ steps.calculate.outputs.result }}'

        
